# generated by zon2nix (https://github.com/Cloudef/zig2nix)

{ linkFarm, fetchzip }:

linkFarm "zig-packages" [
  {
    name = "12209a6b28acfa4bb5d23fa2ab5229acce50e5329e1581bc68f0be3e763dbf222907";
    path = fetchzip {
      url = "https://pkg.machengine.org/mach/3b180a58d55a8af3b8e3f6d87c9ff6f8d082c62c.tar.gz";
      hash = "sha256-cXsZCjVjBJL1gIyRj6b9q2n5LzzlrGPHDNZ6ycIIggI=";
    };
  }
  {
    name = "1220d252360b3ddb0e9a3d813f179142a455c089eccdfdb5e4615b6d39fab5e23e96";
    path = fetchzip {
      url = "https://pkg.machengine.org/mach-ecs/7267d8eb26ced985f65d4526770e96af488d007c.tar.gz";
      hash = "sha256-LiVsZ4vpR6i9hq4qZXx6MhC/sw9O/8kMS/TbMrRSOJA=";
    };
  }
  {
    name = "122096b39d9266d275b780df4d63b1afe6e9a3726f19766baf74b34af3f092532cd3";
    path = fetchzip {
      url = "https://pkg.machengine.org/mach-core/cce02fb96ca787378289c5855b381f0ca9f3e090.tar.gz";
      hash = "sha256-5p2LqIvYfN/ey1zxDh5yjUTMMaOtKYu+Odr0M8/Miy4=";
    };
  }
  {
    name = "12207562ecd84ebeefaabb9e33bd874d03e9d47cb44d95bc61384838df0fd3a26834";
    path = fetchzip {
      url = "https://pkg.machengine.org/mach-core-example-assets/550f31210d806af0fc0d03f38ec70bec51f7b83b.tar.gz";
      hash = "sha256-mgi1W0SSWbovCP4k3eFkGMGmvojr334QN3jW+LT+qSU=";
    };
  }
  {
    name = "1220d4b32bf9d74efb498a939b81b5f1c77bea213a346b88d06ae079836d2dc84aff";
    path = fetchzip {
      url = "https://pkg.machengine.org/mach-model3d/8d94416c815e9f151806e87b9daa54111a7d6d39.tar.gz";
      hash = "sha256-GQ6gHt7U/Mcg+WuisFz61UUlsTALCSEucfTWySXGjV8=";
    };
  }
  {
    name = "1220187935c4c5d4cf824927df28e858dcd06cb864bb5d6be4cd349d2836abb4aec4";
    path = fetchzip {
      url = "https://pkg.machengine.org/mach-sysjs/bafd6c9b8fd5e7be1e8e24cfbd156703d6026aa8.tar.gz";
      hash = "sha256-HrU+7fTbcYk6tlBkkrxDrzs3mzqtTDc8s/EHZciQeE0=";
    };
  }
  {
    name = "122033bae174097c3236afaf934f56c35abfa7b68238abacc4a7df9c0ff43c29ed2e";
    path = fetchzip {
      url = "https://pkg.machengine.org/mach-gamemode/a020ce1fedb5154491beda630c32ba75114c7fb3.tar.gz";
      hash = "sha256-0VCBN821Wc5iaY7I8321zXR5aNvtwM4kTdtO05kogk4=";
    };
  }
  {
    name = "1220d0bf732d8291b8629ce7e115efb6adef84dcc1218317ee0a89a6f1663153f2a9";
    path = fetchzip {
      url = "https://pkg.machengine.org/mach-dusk/ee8abd31daefa617832c590d61c1e1d665a5e55a.tar.gz";
      hash = "sha256-C8om8RuVmg1nzgnnJcC+zG1dLQwFE/Q/Czyv3QXVnNo=";
    };
  }
  {
    name = "122080249197eef2dc5290874ead429285741bcd509b57badc22b716f2630d78149e";
    path = fetchzip {
      url = "https://pkg.machengine.org/vulkan-zig-generated/b2cb02b98b5359d714006ea07502ee02b7d9a353.tar.gz";
      hash = "sha256-1mYPqsc5mauj+mi2q6XsHrVIa/EaCk0PDUHIwWgSoDs=";
    };
  }
  {
    name = "12207ae0264760e850554e47a71124dd0156e86785510662f87a268b222c10a86206";
    path = fetchzip {
      url = "https://pkg.machengine.org/mach-gpu/724787c4339f32537550b23f50acb345f7e17f16.tar.gz";
      hash = "sha256-+A8P21CEp7+goOxJ2dSm0d8yY1R8I0TI3zY/GAqnu1Y=";
    };
  }
  {
    name = "1220533928f944fe59f6dd2807db71cd69108cc810101e627835c3abcc4afea4fb06";
    path = fetchzip {
      url = "https://pkg.machengine.org/mach-glfw/20d247fa4b70c0b3951cb3c439d3466f204754e1.tar.gz";
      hash = "sha256-GsXF2hh2vE3DokPooJ6NU8O/nxv25VPv0gbBAL8uYQg=";
    };
  }
  {
    name = "122020d1ba277ff9e4b5ffff3e3bf4a3c98eeaec821e2a497d031070b05f7814b91f";
    path = fetchzip {
      url = "https://pkg.machengine.org/glfw/49d153ebfc4f45eacc757ec2b063decbf5bb1779.tar.gz";
      hash = "sha256-huH25kTxXkUYS8JCLGEeNXcwzit2lWPfiY48VG5qbRU=";
    };
  }
  {
    name = "122051b3c616c62d55a82207c1cb76e2264b26e8378f56b1e5376d7684bd13616589";
    path = fetchzip {
      url = "https://pkg.machengine.org/xcode-frameworks/8a920385383cc4c0a2a4f55b084d402a9400a5a8.tar.gz";
      hash = "sha256-SHMtZH26rnoBjCLWZA+ov10N0ksifkDil9BOPX2M1Q0=";
    };
  }
  {
    name = "12209e716013e33618aaf5d915c6f2d196922b36aa16e06b52d7c28eafb2b3da0f4e";
    path = fetchzip {
      url = "https://pkg.machengine.org/vulkan-headers/1feb2d841870f7461c28b95549cb707440226138.tar.gz";
      hash = "sha256-6VGAxt1hOp0eG5bBxoTII/HgcsurqWzl4FhXvKKEjUA=";
    };
  }
  {
    name = "1220552bb224e57205049e1c47be8d078a3dc09cb772c0c2e9dea09e452d0c5d6adf";
    path = fetchzip {
      url = "https://pkg.machengine.org/wayland-headers/651515e2d6deb69f0e5ddc39e6f921b33abaf9d6.tar.gz";
      hash = "sha256-MzrkXHuR0CVIZnblKp2Q/Aq+4dzuRxOGY4hcZNz7/HM=";
    };
  }
  {
    name = "12208aaa9355611470ae1357dfa2fd8c86e61679c2a9d343a8afaf25d3826a893111";
    path = fetchzip {
      url = "https://pkg.machengine.org/x11-headers/d5594ef666e51b2531511a15db03b5439e4c11e5.tar.gz";
      hash = "sha256-Suldl/ldNddG3SU/vfZt5MnR+8yJb4WLiJheUJCvLUE=";
    };
  }
  {
    name = "1220bbdbedab9568a37795090e38341c241fe0e22131b8e882bc02954c4b87eecdf3";
    path = fetchzip {
      url = "https://pkg.machengine.org/mach-gpu-dawn/6273d7f31a07fc685e8b4049ba467be071227a71.tar.gz";
      hash = "sha256-w0j0dRNLkyRJRxRmb+2kx7PeVWTaowCpcTgPr0CmDYI=";
    };
  }
  {
    name = "122098cc0b0a39d24aaffcd6d5556e8f31f5dd1a754559ffa468918f2ed6c1ad0a03";
    path = fetchzip {
      url = "https://pkg.machengine.org/direct3d-headers/9617cfd497fae598610a7b0a4be0b035e7308e93.tar.gz";
      hash = "sha256-NyKRAP0dy557rZo9tpdhoUtKlUzKWOxve95p5V9o1w4=";
    };
  }
  {
    name = "122039b4af1d6006d2daa48547a6224464fbc5d69d480a54a9c8f92dfe4a555d1af6";
    path = fetchzip {
      url = "https://pkg.machengine.org/mach-objc/52ce29436bc43e69d84cb48ba8f0b1b284847125.tar.gz";
      hash = "sha256-W9yCajJbrZnlMXeTPBeyHiYWzi/lFIXXJhec0iMibsI=";
    };
  }
  {
    name = "12202044ed9fd69af156b0afde619ffd1d111554c557f57ab670ca9960e76d60d0b8";
    path = fetchzip {
      url = "https://pkg.machengine.org/xcode-frameworks/e77a5c6809a0d3f62ec549ee56e9d2dc6807cd5b.tar.gz";
      hash = "sha256-JgNR98iciq1ucv0e/N87NS3TiyFuFd5KRiML2p/pC34=";
    };
  }
  {
    name = "1220fbe0d105e6cb85c02572cb7510057c3fa7aceee4f0d877dccbd76d484709d892";
    path = fetchzip {
      url = "https://pkg.machengine.org/mach-gpu/fcd1c3d54dface0968d554795cf39cc644d55278.tar.gz";
      hash = "sha256-Il1HO3VX6QpMg03991gRoihv5JcdA9MsfxefX4GROIY=";
    };
  }
  {
    name = "12209d26c597b7ce8be2b5d69389c43bbcf08144431c294782b30fdd0047e114e600";
    path = fetchzip {
      url = "https://pkg.machengine.org/mach-gpu-dawn/16b234c1aae36469b71b640bcfbe4967f1086260.tar.gz";
      hash = "sha256-/iw17pB0+CF0hGA1VXxcxG8vjX0mIu6Z8HYneR0J6BU=";
    };
  }
  {
    name = "1220db419f993fe9204580f761f8d805a9cb07fa910f182899089ad0f4873bfd8b49";
    path = fetchzip {
      url = "https://pkg.machengine.org/mach-basisu/30897f45e8d2d58ac90f1e8fbe15ceabe2127adb.tar.gz";
      hash = "sha256-vuFl55QoHHc//utg5Tl4urxdT7S0DHR0jIE3g1HkPto=";
    };
  }
  {
    name = "122025ad0448f4c1234002cc242d2497cb8649bdefb279411589f3a355a6db3f4bf7";
    path = fetchzip {
      url = "https://pkg.machengine.org/basisu/3490ab25a19d7fdb9ddb0cc924d44204f0e6a940.tar.gz";
      hash = "sha256-aS4hXTCdTp2jO3QwSx8bdgQ18qnlq4U5W7YLqc+O04s=";
    };
  }
  {
    name = "1220a547d08517c7be1b3b0fd2806a399cb71d4189ab5a794f58570af215adc3903a";
    path = fetchzip {
      url = "https://pkg.machengine.org/mach-sysaudio/ec0d3e4a9f053163b4b99ca96d10fd1912563b55.tar.gz";
      hash = "sha256-2ik1i4cVyXx5WuiRr3h2mL76I2i5GdQnLtQDL3kgN6A=";
    };
  }
  {
    name = "122052c4415f4d5be98e3324083939af644d5f8eddd2e6a1a544596645eda8cf411a";
    path = fetchzip {
      url = "https://pkg.machengine.org/linux-audio-headers/6b182ff9d51009ca903f3bac63777fbfa654e5f5.tar.gz";
      hash = "sha256-yo1nS7ST79WBUKTudSe4QQcDU9gBhYZPmShaKeKqcc8=";
    };
  }
  {
    name = "1220e0de43cacb583b8f9efddcbe359398cfca17a39e265b56c8f2a10314eb8f7a5f";
    path = fetchzip {
      url = "https://pkg.machengine.org/mach-freetype/a6d971285dfe731e49f82e81c81da2b7f5c6a442.tar.gz";
      hash = "sha256-E87A0XO3e6c2KhJfSXVoua1RnwQZqR1hC/Cwce4gwDE=";
    };
  }
  {
    name = "12206ed50a939287c717f76547baf24e54301de4500505c19f10965ef559619baf10";
    path = fetchzip {
      url = "https://pkg.machengine.org/freetype/fa33c2db730c0e888046e863b5550ddc3d24e739.tar.gz";
      hash = "sha256-lO4s9XwuM0Jtl3qB7OQ1ObupfGrW83DsxS4UBZ6DVLM=";
    };
  }
  {
    name = "1220682fcfe1caaa9160a6e6243821c21f0c080e4150c9e100f81e969a407a34d432";
    path = fetchzip {
      url = "https://pkg.machengine.org/brotli/13f8e428c00cc28b051f5c05e528b0ab65b0c834.tar.gz";
      hash = "sha256-b4qRZq/TxMLDme4klxfjcqnOaXVNzEo9Cu5S9ZZyV48=";
    };
  }
  {
    name = "1220995d89d65595371320b0609b9f51b363ba795b7ad64fdff050b8c751f90a8792";
    path = fetchzip {
      url = "https://pkg.machengine.org/harfbuzz/84d3479f20c277b90dbd0a97ab44b57851afd9e9.tar.gz";
      hash = "sha256-2OctFNSAjwLcqtV6+dxfKr97K9vX2VQGC/tn1OQmdjY=";
    };
  }
  {
    name = "122008070b460fcb5d513362fd9ee21cda3e8984920ca4239f6190cedda1ea2b8de8";
    path = fetchzip {
      url = "https://pkg.machengine.org/font-assets/4c6ed096d705fb98f811f010ca1237a260c88617.tar.gz";
      hash = "sha256-PjJL8gOIVXeNazzKY2VDmbB3+OoRFM8im5uDZiEcQEM=";
    };
  }
]
