name: automation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: |
          nix run .#mach.update
          nix run .#test.all
      - uses: test-room-7/action-update-file@v1.8.0
        with:
          file-path: versions.json
          commit-msg: Update versions.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: test-room-7/action-update-file@v1.8.0
        with:
          file-path: mach-binaries.json
          commit-msg: Update mach-binaries.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: test-room-7/action-update-file@v1.8.0
        with:
          file-path: README.md
          commit-msg: Update README
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: test-room-7/action-update-file@v1.8.0
        with:
          file-path: templates/**
          commit-msg: Update templates
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix run .#update-templates-flake
      - uses: test-room-7/action-update-file@v1.8.0
        with:
          file-path: templates/**
          commit-msg: Update templates rev
          github-token: ${{ secrets.GITHUB_TOKEN }}
