name: automation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: |
          nix run .#update-versions > versions.json
          nix run .#update-templates
          nix run .#test
      - uses: test-room-7/action-update-file@v1.8.0
        with:
          file-path: |
            versions.json
            mach-binaries.json
            README.md
          commit-msg: Mach nominated Zig version update
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix run .#update-templates
      - uses: test-room-7/action-update-file@v1.8.0
        with:
          file-path: templates/**
          commit-msg: Update templates
          github-token: ${{ secrets.GITHUB_TOKEN }}
