name: automation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: |
          nix run .#update-versions > versions.json
          nix run .#update-templates
          nix run .#test
          nix run .#readme > README.md
      - uses: test-room-7/action-update-file@v1.8.0
        with:
          file-path: |
            versions.json
            README.md
          commit-msg: Mach nominated Zig version update
          github-token: ${{ secrets.GH_TOKEN }}
      - run: nix run .#update-templates
      - uses: test-room-7/action-update-file@v1.8.0
        with:
          file-path: templates/**
          commit-msg: Template rev update
          github-token: ${{ secrets.GH_TOKEN }}
