name: automation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  automation:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
      - uses: DeterminateSystems/flakehub-cache-action@main
      - uses: cachix/cachix-action@master
        with:
          name: mach-flake
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipAddingSubstituter: true
      - run: |
          nix run .#mach.update
          nix run .#test.all
      - uses: test-room-7/action-update-file@v1.8.0
        with:
          branch: ${{ github.head_ref || github.ref_name }}
          file-path: versions.json
          commit-msg: Update versions.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: test-room-7/action-update-file@v1.8.0
        with:
          branch: ${{ github.head_ref || github.ref_name }}
          file-path: README.md
          commit-msg: Update README
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: test-room-7/action-update-file@v1.8.0
        with:
          branch: ${{ github.head_ref || github.ref_name }}
          file-path: templates/**
          commit-msg: Update templates
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix run .#mach.update-flakes
      - uses: test-room-7/action-update-file@v1.8.0
        with:
          branch: ${{ github.head_ref || github.ref_name }}
          file-path: templates/**
          commit-msg: Update templates rev
          github-token: ${{ secrets.GITHUB_TOKEN }}
